[package]
name = "fragment"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fragment_render = { path = "./crates/fragment_render", version = "0.1.0" }
