[package]
name = "fragment_render"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
winit = { version = "0.30.5", features = [ "rwh_05" ] }
pollster = "0.4.0"
env_logger = "0.11.5"
log = "0.4.22"
